# Generated by Django 3.0.7 on 2020-06-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postlanguage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlanguage',
            old_name='post',
            new_name='posts',
        ),
    ]
